name: CDK Synth and Upload

on:
  workflow_call:
    inputs:
      env_id:
        required: true
        type: string
      role_to_assume:
        required: true
        type: string

env:
  AWS_REGION: us-east-1

jobs:
  synth-upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          mvn install -DskipTests=true

      - name: Synth CDK
        run: |
          mkdir -p cdk.out
          cdk synth --context env=${{ inputs.env_id }} > cdk.out/cdk-${{ inputs.env_id }}.template.yml

      - name: Commit synthesized template to repo
        run: |
          git config --global user.name "cdk-bot"
          git config --global user.email "cdk-bot@example.com"

          FOLDER="synth-templates/${{ inputs.env_id }}"
          FILE_NAME="cdk-${{ inputs.env_id }}.template.yml"

          mkdir -p $FOLDER
          cp cdk.out/$FILE_NAME $FOLDER/

          git add $FOLDER/$FILE_NAME
          git commit -m "Add synthesized template for ${{ inputs.env_id }}: ${GITHUB_SHA::7}" || echo "No changes to commit"

          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push
