name: CDK Synth and Email Template

on:
  workflow_call:
    inputs:
      env_id:
        required: true
        type: string
      role_to_assume:
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  RECIPIENT_EMAIL: akashreddy6211@gmail.com
  GMAIL_USERNAME: akashreddy6211@gmail.com
  GMAIL_PASSWORD: oqyl ceom aswj kyen 

jobs:
  synth-upload-email:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java, Node, CDK
        run: |
          sudo apt update
          sudo apt install -y npm
          npm install -g aws-cdk
          sudo apt install -y maven
          java -version
          mvn -version

      - name: Setup AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and synth
        run: |
          mvn install -DskipTests=true
          cdk synth --context env=${{ inputs.env_id }} > cdk-${{ inputs.env_id }}.template.yml

      - name: Send Email with Template Attachment
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ env.GMAIL_USERNAME }}
          password: ${{ env.GMAIL_PASSWORD }}
          subject: "[Review Required] CDK Template for ${{ inputs.env_id }}"
          to: ${{ env.RECIPIENT_EMAIL }}
          from: ${{ env.GMAIL_USERNAME }}
          body: |
            Please review the attached CloudFormation template for the '${{ inputs.env_id }}' environment.
          attachments: |
            cdk-${{ inputs.env_id }}.template.yml
