name: CDK Deploy (Auto after PR merge)

on:
  push:
    branches:
      - dev
      - stg

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branch: dev
            env_name: dev
            role_arn: arn:aws:iam::381492133980:role/GitHubAction-AssumeRoleWithAction.
          - branch: stg
            env_name: stg
            role_arn: arn:aws:iam::614056699201:role/Cdk-deploy-dev-demo

    environment: ${{ matrix.env_name }}

    env:
      ENV_ID: ${{ matrix.env_name }}
      AWS_REGION: us-east-1

    steps:
      - name: Exit if not target branch
        if: ${{ github.ref != format('refs/heads/{0}', matrix.branch) }}
        run: echo "Not matching matrix.branch. Skipping..." && exit 0

      - uses: actions/checkout@v3

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ matrix.role_arn }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Node/Maven/Java
        run: |
          npm install -g aws-cdk
          mvn clean install

      - name: CDK Deploy
        run: |
          echo "Deploying to $ENV_ID"
          cdk deploy --require-approval never --context env=${{ env.ENV_ID }}
