name: CDK Synth & Upload + Commit

on:
  workflow_call:
    inputs:
      env_id:
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  synth-and-upload:
    runs-on: ubuntu-latest

    env:
      ENV_ID: ${{ inputs.env_id }}
      AWS_REGION: us-east-1
      BUCKET_NAME: test-1-git
      FOLDER_NAME: ${{ inputs.env_id == 'dev' && 'test-sample-1' || 
                      inputs.env_id == 'stg' && 'test-sample-2' || 
                      'test-sample-3' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.11.0
        with:
          maven-version: '3.9.6'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Build CDK project
        run: mvn clean install

      - name: Synth CDK and save output
        run: |
          mkdir -p cfn
          TEMPLATE=cfn/cdk-${ENV_ID}.template.yml
          cdk synth --context env=${ENV_ID} > $TEMPLATE
          echo "✅ Synth complete: $TEMPLATE"

      - name: Configure AWS Credentials (dev only)
        if: env.ENV_ID == 'dev'
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::381492133980:role/GitHubAction-AssumeRoleWithAction.
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3 (dev only)
        if: env.ENV_ID == 'dev'
        run: |
          FILE_NAME=${ENV_ID}-test-demo-stack-${GITHUB_SHA::7}.yml
          aws s3 cp cfn/cdk-${ENV_ID}.template.yml \
            s3://${BUCKET_NAME}/${FOLDER_NAME}/${FILE_NAME} \
            --region $AWS_REGION

      - name: Commit synthesized template to repo
        run: |
          git config --global user.name "cdk-bot"
          git config --global user.email "cdk-bot@example.com"

          git pull --rebase

          FILE=cfn/cdk-${ENV_ID}.template.yml
          git add $FILE

          if git diff --cached --quiet; then
            echo "🟡 No changes to commit."
          else
            git commit -m "Update CDK template for ${ENV_ID}: ${GITHUB_SHA::7}"
            git push
            echo "✅ Committed synthesized template to GitHub."
          fi
