name: Main Validation and Synth Trigger

on:
  pull_request:
    branches:
      - dev
      - stg

jobs:
  validate-and-trigger:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Determine environment
        id: env
        run: |
          TARGET_BRANCH="${{ github.base_ref }}"
          if [[ "$TARGET_BRANCH" == "dev" ]]; then
            echo "env_id=dev" >> $GITHUB_OUTPUT
            echo "role_to_assume=arn:aws:iam::381492133980:role/GitHubAction-AssumeRoleWithAction" >> $GITHUB_OUTPUT
          elif [[ "$TARGET_BRANCH" == "stg" ]]; then
            echo "env_id=stg" >> $GITHUB_OUTPUT
            echo "role_to_assume=arn:aws:iam::614056699201:role/Cdk-deploy-dev-demo" >> $GITHUB_OUTPUT
          else
            echo "Invalid target branch: $TARGET_BRANCH"
            exit 1
          fi

      - name: Trigger synth + email workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: cdk-synth-upload.yml
          ref: ${{ github.base_ref }}
          inputs: 
            env_id: ${{ steps.env.outputs.env_id }}
            role_to_assume: ${{ steps.env.outputs.role_to_assume }}
